files: ^src/, ^utils/
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: trailing-whitespace
          - id: check-ast
          - id: check-yaml
          - id: end-of-file-fixer
          - id: fix-encoding-pragma
          - id: mixed-line-ending
          - id: detect-private-key
    - repo: https://github.com/psf/black
      rev: 21.12b0
      hooks:
          - id: black
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            args: [--profile=black]
    - repo: https://github.com/pycqa/pylint
      rev: pylint-2.6.0
      hooks:
          - id: pylint
            args:
                - --fail-under=3
                - --max-line-length=80
