domains = [
    "complexity theory",
    "reinforcement learning",
    "deep learning",
    "machine learning",
    "intelligence",
    "space exploration",
    "astronomy",
    "cognitive neuroscience",
    "complex socio-technical systems",
    "smart cities",
    "genetics",
    "diversity",
    "equity",
    "network science",
    "evolutionary theory",
    "optimization algorithms",
    "causality",
    "statistics",
    "recommender systems",
    "chaos theory",
    "innovation",
    "non linear dynamics",
    "artificial life",
    "astrophysics",
    "electronics",
    "internet of things",
    "federated machine learning",
    "marketing",
    "philosophy",
    "psychology",
    "ethics",
    "aesthetics",
    "urban mobility",
    "computational social science",
    "politics",
    "robotics",
    "game theory",
    "autonomous vehicles",
    "network dynamics",
    "system design",
    "information diffusion",
    "adaptive intelligent systems",
]

content = [
    "atomic habits",
    "introducing game theory: a graphic guide",
    "statistical rethinking: a bayesian course with",
    "novacene: the coming age of hyperintelligence",
]
