name: Code Coverage
on: [push]
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Setup Python
              uses: actions/setup-python@master
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  pip install -r ./requirements.txt
            - id: auth
              name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
            - name: Run tests and generate test coverage report
              env:
                  TWITTER_API_BEARER_TOKEN: ${{ secrets.TWITTER_API_BEARER_TOKEN }}
              run: |
                  pytest --cov=./src --cov-report=xml
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1.0.3
              with:
                  token: ${{secrets.CODECOV_TOKEN}}
                  file: ./coverage.xml
                  flags: unittests
                  name: codecov-umbrella
