name: Code Coverage
on: [push]
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Setup Python
              uses: actions/setup-python@master
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  pip install -r ./requirements.txt
            - name: Export GCP default credentials
                uses: google-github-actions/setup-gcloud@master
                with:
                  service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
                  service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
                  export_default_credentials: true
            - name: Run tests and generate test coverage report
              env:
                  TWITTER_API_BEARER_TOKEN: ${{ secrets.TWITTER_API_BEARER_TOKEN }}
              run: |
                  pytest --cov=./src --cov-report=xml
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1.0.3
              with:
                  token: ${{secrets.CODECOV_TOKEN}}
                  file: ./coverage.xml
                  flags: unittests
                  name: codecov-umbrella
