name: Code Coverage
on: [push]
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Setup Python
              uses: actions/setup-python@master
              with:
                  version: 3.7
            - name: Generate coverage report
              env:
                  TWITTER_API_BEARER_TOKEN: ${{ secrets.TWITTER_API_BEARER_TOKEN }}
              run: |
                  pip install -r ./projects/twitter/requirements.txt
                  pytest --cov=./projects/twitter/src --cov-report=xml
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1.0.3
              with:
                  token: ${{secrets.CODECOV_TOKEN}}
                  file: ./coverage.xml
                  flags: unittests
                  name: codecov-umbrella
